### PR TITLE
Oscal 1 0.0

### PR DESCRIPTION
**Pull request by openprivacy**
This seems to work

### CODE REVIEW

**Comment by openprivacy** [comment]
Easy (non-conclusive) test for multiple components:
```
cd ..
git clone git@github.com:CivicActions/ssp-toolkit.git
cd compliance-io
poetry run python examples/oc_to_oscal_components.py ../civicactions/ssp-toolkit/opencontrol/opencontrol.yaml
```

**Comment by woodt** [comment]
So this looks pretty good, I think :-)  There were a bunch of formatting and lint errors that I fixed and pushed.  You should install pre-commit!  I did *NOT* get a chance to fix the mypy errors, though, so this PR still needs some work.  In order for me to commit/push my fixes, I _disabled_ the mypy hook in `.pre-commit-config.yml`.  You should uncomment that hook to reenable it, and then run `pre-commit run --all`.

**Review by woodt — CHANGES_REQUESTED** [review]
Address mypy lint errors.

**Comment by openprivacy** [comment]
I'm obviously out of practice. How do I review your change request? (I just pushed some more updates that get the test_oscal_ssp to produce valid code...)

**Comment by openprivacy** [comment]
Those are some awesome pre-commit hooks - thanks for shooting them my way. Code is cleaner and more correct now - ready for your consideration.

**Review by woodt — APPROVED** [review]

**Pull request merged**
